name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: pill_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black
    
    - name: Code formatting check
      run: |
        black --check app/ --diff
        flake8 app/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Set up environment variables
      run: |
        echo "LINE_CHANNEL_ACCESS_TOKEN=test_token" >> $GITHUB_ENV
        echo "LINE_CHANNEL_SECRET=test_secret" >> $GITHUB_ENV
        echo "GEMINI_API_KEY=test_key" >> $GITHUB_ENV
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_USER=root" >> $GITHUB_ENV
        echo "DB_PASS=testpassword" >> $GITHUB_ENV
        echo "DB_NAME=pill_test" >> $GITHUB_ENV
        echo "SECRET_KEY=test-secret-key" >> $GITHUB_ENV
        echo "YOUR_BOT_ID=@test_bot" >> $GITHUB_ENV
        echo "LIFF_CHANNEL_ID=test_liff" >> $GITHUB_ENV
    
    - name: Wait for MySQL
      run: |
        timeout 60 bash -c 'until mysqladmin ping -h"127.0.0.1" -P"3306" -uroot -ptestpassword --silent; do sleep 1; done'
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=app --cov-report=xml --cov-report=html
      continue-on-error: true
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        pip install bandit safety
    
    - name: Run Bandit Security Scan
      run: |
        bandit -r app/ -f json -o bandit-report.json || true
        bandit -r app/ -f txt
    
    - name: Run Safety Check
      run: |
        safety check --json --output safety-report.json || true
        safety check
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: |
          bandit-report.json
          safety-report.json

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t linebot-app:test .
    
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 8080:8080 \
          -e LINE_CHANNEL_ACCESS_TOKEN=test \
          -e LINE_CHANNEL_SECRET=test \
          -e GEMINI_API_KEY=test \
          -e SECRET_KEY=test \
          linebot-app:test
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container

  deploy-staging:
    needs: [test, security-scan, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and push to staging
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:staging-${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:staging-${{ github.sha }}
    
    - name: Deploy to Cloud Run Staging
      run: |
        gcloud run deploy linebot-app-staging \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:staging-${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars="LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          --set-env-vars="LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" \
          --set-env-vars="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
          --set-env-vars="DB_HOST=${{ secrets.DB_HOST }}" \
          --set-env-vars="DB_USER=${{ secrets.DB_USER }}" \
          --set-env-vars="DB_PASS=${{ secrets.DB_PASS }}" \
          --set-env-vars="DB_NAME=${{ secrets.DB_NAME }}" \
          --set-env-vars="SECRET_KEY=${{ secrets.SECRET_KEY }}" \
          --tag staging

  deploy-production:
    needs: [test, security-scan, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and push to production
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:prod-${{ github.sha }} .
        docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:prod-${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:prod-${{ github.sha }}
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:latest
    
    - name: Deploy to Cloud Run Production
      run: |
        gcloud run deploy linebot-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/linebot-app:prod-${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars="LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          --set-env-vars="LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" \
          --set-env-vars="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
          --set-env-vars="DB_HOST=${{ secrets.DB_HOST }}" \
          --set-env-vars="DB_USER=${{ secrets.DB_USER }}" \
          --set-env-vars="DB_PASS=${{ secrets.DB_PASS }}" \
          --set-env-vars="DB_NAME=${{ secrets.DB_NAME }}" \
          --set-env-vars="SECRET_KEY=${{ secrets.SECRET_KEY }}" \
          --tag production
    
    - name: Notify deployment success
      run: |
        echo "🚀 Production deployment successful!"
        echo "Service URL: $(gcloud run services describe linebot-app --region=us-central1 --format='value(status.url)')"